cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'wget'
brew 'yarn', args: ['without-node']

cask '1password'
cask 'cleanmymac'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'hyper'
cask 'kap'
cask 'notion'
cask 'postman'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
